name: ulti-lora-backplane
version: 0.0.1
summary: TTN LoRa Packet Forwarder
description: Collection of packages required for LoRa Packet Forwarding

confinement: devmode
build-packages: [protobuf-compiler, libprotobuf-dev, libprotoc-dev, automake, libtool, autoconf, python-dev, make]

parts:
  lora_gateway:
    plugin: autotools
    source-type: git
    source: https://github.com/kersing/lora_gateway.git
  protobuf-c:
    plugin: autotools
    source-type: git
    source: https://github.com/kersing/protobuf-c.git
  paho-mqtt:
    plugin: autotools
    source-type: git
    source: https://github.com/kersing/paho.mqtt.embedded-c.git
  ttn-gateway-connector:
    plugin: autotools
    source-type: git
    source: https://github.com/kersing/ttn-gateway-connector.git
  packet_forwarder:
    plugin: autotools
    source-type: git
    source: https://github.com/kersing/packet_forwarder.git

apps:
  packet-forwarder:
    command: packet_forwarder
