name: ulti-lora-backplane
version: 0.2.3
summary: TTN LoRa Packet Forwarder
description: Collection of packages required for LoRa Packet Forwarding

confinement: classic
build-packages: [protobuf-compiler, libprotoc-dev, libprotobuf-dev, automake, libtool, autoconf, python-dev, make, libprotobuf-c-dev, libc6-dev]

parts:
   loragateway:
    plugin: make
    source-type: git
    source: https://github.com/ryanteck/lora_gateway-1
    #source-subdir: libloragw/
    build:
      make all -e -C libloragw
    artifacts:
      - libloragw/*
    install: |
      mkdir $SNAPCRAFT_PART_INSTALL/lib/
      mkdir $SNAPCRAFT_PART_INSTALL/lib/libloragw
      cp -r libloragw $SNAPCRAFT_PART_INSTALL/lib/

   protobuf-c:
    plugin: make
    source-type: git
    source: https://github.com/kersing/protobuf-c.git
    build-packages: [libprotobuf-c-dev,libprotobuf-dev, protobuf-c-compiler, libprotoc-dev]
    build: |
      ./autogen.sh
      ./configure LIBS="-I$SNAPCRAFT_STAGE/src/google/protobuf/compiler/"
      make protobuf-c/libprotobuf-c.la
      mkdir bin
      ./libtool install /usr/bin/install -c protobuf-c/libprotobuf-c.la `pwd`/bin
      rm -f `pwd`/bin/*so*

    install: |
      mkdir $SNAPCRAFT_PART_INSTALL/lib/
      cp -r . $SNAPCRAFT_PART_INSTALL/lib/protobuf-c
      sudo make install

    after:
      - loragateway
   paho.mqtt.embedded-c:
    plugin: make
    source-type: git
    source: https://github.com/kersing/paho.mqtt.embedded-c.git
    after:
      - protobuf-c
    build:
      make
    install: |
      mkdir $SNAPCRAFT_PART_INSTALL/lib/
      cp -r . $SNAPCRAFT_PART_INSTALL/lib/paho.mqtt.embedded-c/
      sudo make install
    prepare:
      sudo rm /usr/local/lib/libpaho-embed-mqtt3c.so  || true
    #make-install-var: /usr/local/lib/
   ttn-gateway-connector:
    plugin: make
    source-type: git
    source: https://github.com/ryanteck/ttn-gateway-connector.git
    prepare: |
      git clone https://github.com/google/protobuf.git
      cp config.mk.in config.mk
    artifacts:
      - bin/libttn-gateway-connector.so
    install: |

      mkdir $SNAPCRAFT_PART_INSTALL/lib/
      cp bin/libttn-gateway-connector.so $SNAPCRAFT_PART_INSTALL/lib/libttn-gateway-connector.so
      cp -r . $SNAPCRAFT_PART_INSTALL/lib/ttn-gateway-connector/
    after:
      - paho.mqtt.embedded-c
   packetforwarder:
    plugin: make
    source-type: git
    source: https://github.com/kersing/packet_forwarder.git
    build-packages: [libc6-dev, libc6]
    #source-subdir: mp_pkt_fwd

    make-parameters:
      - LGW_PATH=$SNAPCRAFT_STAGE/lib/libloragw
      - TTN_INC=-I$SNAPCRAFT_STAGE/lib/ttn-gateway-connector/src -I$SNAPCRAFT_STAGE/lib/ttn-gateway-connector/src/github.com/gogo/protobuf/protobuf/ -I$SNAPCRAFT_STAGE/lib/ttn-gateway-connector/src/github.com/TheThingsNetwork -I$SNAPCRAFT_STAGE/libprotobuf-c
      - LIBS += -L$SNAPCRAFT_STAGE/lib/paho.mqtt.embedded-c/build/output -lpaho-embed-mqtt3c -L$SNAPCRAFT_STAGE/lib/ttn-gateway-connector/bin -lttn-gateway-connector -L$SNAPCRAFT_STAGE/lib/protobuf-c/bin -lprotobuf-c -lloragw -lrt -lpthread -lm

    after:
      - ttn-gateway-connector
      - loragateway
      - paho.mqtt.embedded-c
      - protobuf-c
    artifacts:
      - mp_pkt_fwd/mp_pkt_fwd

apps:
  packet-forwarder:
    command: mp_pkt_fwd/mp_pkt_fwd
