name: ulti-lora-backplane
version: 0.0.1
summary: TTN LoRa Packet Forwarder
description: Collection of packages required for LoRa Packet Forwarding

confinement: devmode
build-packages: [protobuf-compiler, libprotobuf-dev, libprotoc-dev, automake, libtool, autoconf, python-dev, make, libprotobuf-c-dev]

parts:
  loragateway:
    plugin: make
    source-type: git
    source: https://github.com/ryanteck/lora_gateway.git
    source-subdir: libloragw/
    make-parameters:
      - libloragw.a
    artifacts:
      - ../libloragw
    stage:
      - libloragw
  paho.mqtt.embedded-c:
    plugin: make
    source-type: git
    source: https://github.com/kersing/paho.mqtt.embedded-c.git
    after:
      - loragateway
    build:
      make
    install:
      sudo make install
    #make-install-var: /usr/local/lib/
  ttn-gateway-connector:
    plugin: make
    source-type: git
    source: https://github.com/ryanteck/ttn-gateway-connector.git
    prepare:
      cp config.mk.in config.mk
    artifacts:
      - bin/libttn-gateway-connector.so
    after:
      - paho.mqtt.embedded-c
  packetforwarder:
    plugin: make
    source-type: git
    source: https://github.com/kersing/packet_forwarder.git
    source-subdir: mp_pkt_fwd
    prepare:
      pwd
    make-parameters:
      - LGW_PATH="$SNAPCRAFT_STAGE/usr/local/libloragw"
      - TTN_INC="-I../../../../ttn-gateway-connector/build/src -I../../../ttn-gateway-connector/build/github.com/gogo/protobuf/protobuf -I../../ttn-gateway-connector/src/github.com/TheThingsNetwork -I../../protobuf-c"

    after:
      - ttn-gateway-connector

apps:
  packet-forwarder:
    command: packet_forwarder
